spring:
  datasource:
    username: root
    password: Harsh@123
    url: jdbc:mysql://localhost:3306/movie
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${mail.username}"
    password: "${mail.password}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

project:
  poster: src/main/resources/static/posters/

base:
  url: "http://localhost:8080"

server:
  port: 8081  
